### ISSUE TITLE
SparkSQL & metastore调优

### ISSUE THREAD

**Issue by zhoukangcn** [zhoukangcn/blog#4]
## 背景

目前的体系中，SparkSQL主要提供给ad-hoc类的OLAP查询。SparkSQL通过metastore获取hive表信息，因而可以直接查询Hive表的数据。metastore的性能直接影响SparkSQL的查询速度。

这次的问题是从用户上报的一个case（属于第一类问题）开始追查，过程中出现了很多和“想象”的场景不一样的情况。最终的结果可能很简单，过程中使用到的工具值得总结一下。

**版本信息**

Hive：基于社区`1.2.2`的内部版本，使用Apache Sentry做权限校验（`AuthorizingObjectStoreV2`）

Spark：基于社区`2.3.2`的内部版本。

Sentry：基于社区`1.7.1`的内部版本。

## 问题

用户上报了一个case，在使用spark thrift server来执行SparkSQL时执行时间异常，在分析语法阶段耗时超过60s，疑似是metastore的问题。

查询SQL为：

```
select sum(v1) from db_d1.table_t1 where date=20200427 and  cast(effective_date/100 as int)=201507 and (cast(clear_date/100 as int) >= 201507 or clear_date=19700101);
```

Spark driver日志显示Analyzing阶段花费76s，但是没有更多的日志显示耗时细节。

```
Parsing 3ms (total 3ms)
Analyzing 76537ms (total 76537ms)
Authorizing 1196ms (total 1196ms)
Optimizing 1613ms (total 1613ms)
Planning 8ms (total 8ms)
```

### 关键信息

好在内部的Spark做了修改，会截取jstack保存到日志中。在spark.log中找到处理该请求的thread-id，在通过thread-id查找jstack日志，找到长时间停留的堆栈，从而发现了关键信息：

```
at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_partitions_ps_with_auth(ThriftHiveMetastore.java:2156)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_partitions_ps_with_auth(ThriftHiveMetastore.java:2138)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.listPartitionsWithAuthInfo(HiveMetaStoreClient.java:1139)
```

SQL的处理线程长时间停留在了listPartitionsWithAuthInfo，接口功能是获取表的分区列表。从metastore日志中找到的相关请求：

```
(HiveMetaStore.java:logInfo(803)) - 633: get_partitions_ps_with_auth : db=db_d1 tbl=table_t1[]
```

注意到这里的参数：`tbl=table_t1[]`，表后面的`[]`表示传参的part_vals为空数组，原始函数定义如下：

```
public List<Partition> get_partitions_ps_with_auth(final String db_name,
        final String tbl_name, final List<String> part_vals,
        final short max_parts, final String userName,
        final List<String> groupNames)
```

这里意味着，SparkSQL向metastore请求了该表的所有partition（后统计共有1.7k个分区）。

在用户给出的SQL中，明确表明了需要查询的partition为：`date=20200427`，按道理是不用请求所有partition的。且通过测试对比了请求单个partition和所有partition的耗时对比：

```
db=db_d1 tbl=table_t1[]: 耗时60s
db=db_d1 tbl=table_t1[20200427]：耗时50ms
```

### 为何SparkSQL会请求所有分区

和SparkSQL同事沟通后，得到如下结论：

1. 当文件格式为parquet时，因为用户的schema可能发生变化，SparkSQL需要做schema推断；
2. schema推断的方式是将parquet文件schema与metastore schema进行对比；
3. 获取parquet文件schema需要获得最新的分区中的文件；
4. 因此需要获取所有分区，用来获取最新分区的名称，从而获取到对应的文件；

基本明确了：扫描所有分区其实是为了找到最新的分区。那么优化思路主要为：

1. 是否可以低成本的获得最新的分区？
2. 优化获取所有的分区接口

#### 方式1

最直接的方式：`order by partition desc limit 1` ，metastore确实提供了这样的机制。

```
public List<Partition> get_partitions_ps_with_auth(final String db_name,
        final String tbl_name, final List<String> part_vals,
        final short max_parts, final String userName,
        final List<String> groupNames)
```

`max_parts`参数即为获取分区的数量，默认为-1时，获取所有part_vals中的分区。

hive的配置项`hive.metastore.sort.partitions.by.desc`，默认为false，改为True后可以实现`order by partition desc`

不过，需要注意的是：

1. `hive.metastore.sort.partitions.by.desc`只能在服务端配置，一旦更改会影响所有上层业务；
2. 排序方式发生变化后，若有用户的业务依赖的是排序后的结果，则会受到影响；

#### 方式2

有注意到HiveSQL获取partitions的速度非常快，追踪请求后发现，hiveSQL使用的是`listPartitionNames`，相比获取Partitions要快很多。

至于为何`listPartitionNames`比`listPartitionsWithAuthInfo`快，在下一节进行分析。

### listPartitionsWithAuthInfo的耗时分析及优化

这里借助了java火焰图工具，在试用了多种性能分析工具后选择[async-profiler](https://github.com/jvm-profiling-tools/async-profiler)得到了如下的火焰图。

![202005-image-20200508105321629.png](https://raw.githubusercontent.com/zhoukangcn/blog/master/images/202005-image-20200508105321629.png)

这里有个问题：打印日志发现，耗时占比和火焰图显示的不一致。

1. `ObjectStore.commitTransaction`耗时并不长(1s)。
2. `ObjectStore.convertToPart`会调用很多次，累计时间为60s；

`listPartitionsWithAuthInfo`耗时的主要原因如下：

1. metastore首先会获取该表的所有partition value的集合（比如[20200401, 20200402]）；
2. 需要返回的数据格式形式为`List<Partition>`，因此需要将partition value转换为数据结构`Partition`
3. `Partition`中的一些其他信息需要从数据库（MySQL）中获取
4. 每个partition value都会触发一次数据库交互，由于partition数量多，因而非常的慢；

而`listPartitionNames`无需获取额外的信息，仅返回分区名称。返回数据样例为`[date=20200401, date=20200402]`。

## 总结

- 日志是定位问题的第一现场，尽量关联其上下文
- 对于Hadoop服务，增加日志的成本较大，一般通过jstack等手段帮助分析
- 火焰图是性能调优利器，最好和日志结合分析

**Comment by denglingang** [comment]
周总，耗时占比和火焰图显示的不一致，会是什么原因导致的？
